# Generated by Django 3.1.7 on 2021-04-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_tracking'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpagepersontype',
            name='page',
        ),
        migrations.RemoveField(
            model_name='personpagepersontype',
            name='person_type',
        ),
        migrations.DeleteModel(
            name='PersonType',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='website',
        ),
        migrations.AddField(
            model_name='personindexpage',
            name='call_to_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.calltoactionsnippet'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='person_type',
            field=models.CharField(blank=True, choices=[('curriculum', 'Curriculum & Pedagogy'), ('implementations', 'Program Implementations'), ('partnerships', 'Partnerships'), ('engineering', 'Engineering'), ('UX', 'UX Design & Research'), ('communications', 'Communications'), ('operations', 'Team Operations'), ('board', 'Board of directors'), ('advisory', 'Advisory Board')], max_length=255),
        ),
        migrations.AddField(
            model_name='personpage',
            name='pronouns',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PersonPagePersonType',
        ),
    ]
