# Generated by Django 3.1.7 on 2021-04-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmembers',
            old_name='board_member_bio',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='boardmembers',
            old_name='board_member_image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='boardmembers',
            old_name='board_member_title',
            new_name='title',
        ),
    ]
