# Generated by Django 3.1.7 on 2021-04-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpagepersontype',
            name='page',
        ),
        migrations.RemoveField(
            model_name='personpagepersontype',
            name='person_type',
        ),
        migrations.DeleteModel(
            name='PersonType',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='website',
        ),
        migrations.AddField(
            model_name='personpage',
            name='person_type',
            field=models.CharField(blank=True, choices=[('curriculum', 'Curriculum & Pedagogy'), ('implementations', 'Program Implementations'), ('partnerships', 'Partnerships'), ('engineering', 'Engineering'), ('UX', 'UX Design & Research'), ('communications', 'Communications'), ('operations', 'Team Operations')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PersonPagePersonType',
        ),
    ]
