# Generated by Django 3.1.7 on 2021-04-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210413_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembers',
            name='person_type',
            field=models.CharField(blank=True, choices=[('curriculum', 'Curriculum & Pedagogy'), ('implementations', 'Program Implementations'), ('partnerships', 'Partnerships'), ('engineering', 'Engineering'), ('UX', 'UX Design & Research'), ('communications', 'Communications'), ('operations', 'Team Operations'), ('board', 'Board of directors'), ('advisory', 'Advisory Board')], max_length=255),
        ),
    ]
