# Generated by Django 3.1.7 on 2021-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_customize_people_model_20210407_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='pronouns',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
