# Generated by Django 3.1.7 on 2021-04-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_boardmembers_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembers',
            name='person_type',
            field=models.CharField(blank=True, choices=[('board', 'Board of directors'), ('advisory', 'Advisory Board')], max_length=255),
        ),
    ]
