# Generated by Django 3.1.7 on 2021-04-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20210414_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembers',
            name='person_type',
            field=models.CharField(choices=[('board', 'Board of directors'), ('advisory', 'Advisory Board')], max_length=255),
        ),
    ]
